[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

  # Includes all Markdown files inside the "files/" directory.
  [functions.excluded_files]
    excluded_files = ["src/**"]


[build]
  command = "npm run build"
  # functions build directory
  functions = "functions"
  publish = "public"


# [[redirects]]
#   from = "/"
#   to = "/.netlify/functions/api"
#   status = 200
#
#
# [[redirects]]
#   from = "/static/*"
#   to = "/.netlify/functions/server/static/*"
#   status = 200
